from pathlib import Path
p=Path('/mnt/data/hh/data/products.ts')
s=p.read_text()
marker='\n];\n\nfor (const product of products) {'
items="""
{id:'newmatic-h18-6s',slug:'newmatic-h18-6s-60cm-slim-hood',brand:'Newmatic',model:'H18.6S',image:'https://newmatic.com/wp-content/uploads/2023/11/H18.6S-final.png',name:'60cm Slim Undermount Cooker Hood',category:'Cooker Hoods',description:'Newmatic H18.6S slim undermount hood with touchscreen controls, twin stainless-steel propellers and LED illumination for compact kitchens.',features:['60cm slim hood','3-speed touchscreen control','Twin stainless-steel propellers','2 × 2W LED lights','Ducted or recirculating operation','5-year motor warranty'],specifications:{Type:'60cm slim undermount hood',Control:'Touch control',Airflow:'400 m³/h',Noise:'52 dB',Lighting:'2 × 2W LED',Dimensions:'590 × 500 × 140 mm',Power:'100W'},price:1150000,currency:'UGX',warranty:'1 year appliance; 5 years motor',availability:'in-stock',confidence:'High',imageSource:'Newmatic official exact-model image; Uganda price cross-checked with TilyExpress',imageClean:true,oemVerified:true,oemUrl:'https://newmatic.com/product/h18-6s-slim-undermount-chimney-hood/'},
{id:'newmatic-h76-9s',slug:'newmatic-h76-9s-90cm-curved-chimney-hood',brand:'Newmatic',model:'H76.9S',image:'https://www.kenyatronics.com/product-images/phpcEPPuz_800.jpg',name:'90cm Curved Wall-Mount Chimney Hood',category:'Cooker Hoods',description:'Newmatic H76.9S curved 90cm wall hood with touchscreen control, auto-timer, twin propellers and high airflow for larger cooking areas.',features:['90cm wall hood','Patented curved control panel','3-speed touchscreen control','Delay/auto-timer','Twin stainless-steel propellers','760 m³/h airflow','2 × 2W LED lights','Ducted or recirculating operation'],specifications:{Type:'90cm curved wall hood',Control:'Touch control',Airflow:'760 m³/h',Noise:'54 dB',Lighting:'2 × 2W LED',Dimensions:'900 × 480 × 480–810 mm'},price:1700000,currency:'UGX',warranty:'1 year appliance; 5 years motor',availability:'in-stock',confidence:'High',imageSource:'Clean exact-model retailer image; Uganda exact-model price/availability cross-checked with Jumia Uganda and official Newmatic Uganda specifications',imageClean:true,oemVerified:true,oemUrl:'https://newmaticug.com/product/h76-9s-kitchen-chimney-hood/'},
{id:'hisense-hho60pass',slug:'hisense-hho60pass-60cm-extractor-hood',brand:'Hisense',model:'HHO60PASS',image:'https://www.dombelo.com/wp-content/uploads/2024/03/Hisense-HHO60PASS-Extractor-%E2%80%93-60cm-Under-Cabinet-Cooker-Hood-3.jpg',name:'60cm Stainless Steel Extractor Hood',category:'Cooker Hoods',description:'Hisense HHO60PASS 60cm under-cabinet extractor hood with stainless-steel body, three-speed control and LED lighting.',features:['60cm under-cabinet hood','Stainless-steel body','3-speed operation','LED lighting','Washable filters','Ducted or recirculated extraction'],specifications:{Type:'60cm under-cabinet extractor hood',Extraction:'200 m³/h',Controls:'3-speed control',Material:'Stainless steel',Lighting:'LED',Width:'60cm'},price:386500,currency:'UGX',warranty:'3 years on current Dombelo listing',availability:'in-stock',confidence:'High',imageSource:'Clean exact-model Dombelo Uganda product image; local price and specifications cross-checked with Dombelo',imageClean:true,oemVerified:false,oemUrl:'https://www.hisense.com/'},
{id:'beko-ctb9250xh',slug:'beko-ctb9250xh-90cm-telescopic-hood',brand:'Beko',model:'CTB9250XH',image:'https://www.beko.com/content/dam/germany-de-aem/germany-de-aemProductCatalog/product-images/8844763200-CTB-9250-XH/8844763200-LO1-20150622-152203.png',name:'90cm Telescopic Cooker Hood',category:'Cooker Hoods',description:'Beko CTB9250XH 90cm telescopic hood with three power levels, LED illumination and dishwasher-safe metal cassette filters.',features:['90cm telescopic hood','3 power levels','LED illumination','2 × 4W LED lamps','Dishwasher-safe metal cassette filters','Charcoal filter support','Mechanical slider control'],specifications:{Type:'Telescopic hood',Width:'89.8 cm',Height:'18 cm',Depth:'28 cm',Airflow:'220–420 m³/h',Noise:'57–69 dBA',EnergyClass:'D',Controls:'Mechanical slider',AnnualEnergy:'88.4 kWh/year'},price:1500000,currency:'UGX',warranty:'2 years on current TilyExpress Uganda listing',availability:'in-stock',confidence:'High',imageSource:'Beko official exact-model image; Uganda price cross-checked with TilyExpress',imageClean:true,oemVerified:true,oemUrl:'https://www.beko.com/ke-en/products/built-in-hoods/hood-90-cm-ctb-9250-xh'},
"""
s=s.replace(marker, '\n'+items+'];\n\nfor (const product of products) {')
s=s.replace("export const categories = ['Refrigerators','Freezers','Washing Machines','Dryers','Cookers','Ovens','Hobs','Small Kitchen'", "export const categories = ['Refrigerators','Freezers','Washing Machines','Dryers','Cookers','Ovens','Hobs','Cooker Hoods','Small Kitchen'")
p.write_text(s)

pt=Path('/mnt/data/hh/types/product.ts')
t=pt.read_text().replace("'Ovens'|'Hobs'|'Small Kitchen'", "'Ovens'|'Hobs'|'Cooker Hoods'|'Small Kitchen'")
pt.write_text(t)

cr=Path('/mnt/data/hh/lib/category-registry.ts')
c=cr.read_text().replace("{ name:'Cooker Hoods', slug:'cooker-hoods', description:'Kitchen extraction hoods with verified dimensions and extraction specifications.', brands:['Samsung','LG','Hisense','Midea'], status:'research-pending' }", "{ name:'Cooker Hoods', slug:'cooker-hoods', description:'Kitchen extraction hoods with verified dimensions and extraction specifications.', brands:['Newmatic','Beko','Hisense','Midea','Blueflame'], status:'active' }")
cr.write_text(c)

nc=Path('/mnt/data/hh/next.config.ts')
n=nc.read_text().replace("{ protocol:'https', hostname:'www.dombelo.com' },", "{ protocol:'https', hostname:'www.dombelo.com' },\n  { protocol:'https', hostname:'www.kenyatronics.com' },")
nc.write_text(n)
