import re
from pathlib import Path
p=Path('/mnt/data/amaal_quick_work/data/products.ts')
s=p.read_text()
marker='\n];\n}\n\n\nexport const categories'
assert marker in s
items = [
{"id":"hoffmans-hm780","slug":"hoffmans-hm780-8l-air-fryer","brand":"Hoffmans","model":"HM-780","name":"Hoffmans 8L Digital Air Fryer HM-780","category":"Quick Cooking","description":"Hoffmans HM-780 8L digital air fryer for family-size air frying and roasting.","features":["8L capacity","Digital controls","Air frying","Adjustable temperature","Timer"],"specifications":{"Capacity":"8L","Power":"2000W","Control":"Digital"},"price":200000,"confidence":"High","imageSource":"Jumia Uganda Hoffmans listing","imageClean":False},
{"id":"hoffmans-hm780a","slug":"hoffmans-hm780a-8l-air-fryer","brand":"Hoffmans","model":"HM-780A","name":"Hoffmans 8L Digital Air Fryer HM-780A","category":"Quick Cooking","description":"Hoffmans HM-780A 8L digital air fryer for everyday family cooking.","features":["8L capacity","Digital controls","Air frying","Adjustable temperature","Timer"],"specifications":{"Capacity":"8L","Power":"2000W","Control":"Digital"},"price":200000,"confidence":"High","imageSource":"Jumia Uganda Hoffmans listing","imageClean":False},
{"id":"hoffmans-hm796","slug":"hoffmans-hm796-8l-air-fryer","brand":"Hoffmans","model":"HM-796","name":"Hoffmans 8L Digital Air Fryer HM-796","category":"Quick Cooking","description":"Hoffmans HM-796 8L digital air fryer for family meals and hot-air cooking.","features":["8L capacity","Digital controls","Air frying","Adjustable temperature","Timer"],"specifications":{"Capacity":"8L","Control":"Digital"},"price":230000,"confidence":"High","imageSource":"Jumia Uganda Hoffmans listing","imageClean":False},
{"id":"hoffmans-hm778","slug":"hoffmans-hm778-10l-air-fryer","brand":"Hoffmans","model":"HM-778","name":"Hoffmans 10L Air Fryer HM-778","category":"Quick Cooking","description":"Hoffmans HM-778 10L air fryer for large-batch hot-air cooking.","features":["10L capacity","Air frying","Adjustable temperature","Timer"],"specifications":{"Capacity":"10L"},"price":450000,"confidence":"High","imageSource":"Jumia Uganda Hoffmans listing","imageClean":False},
{"id":"hoffmans-hm795","slug":"hoffmans-hm795-12l-digital-air-fryer","brand":"Hoffmans","model":"HM-795","name":"Hoffmans 12L Digital Air Fryer HM-795","category":"Quick Cooking","description":"Hoffmans HM-795 12L digital air fryer with dual heating, touchscreen control and viewing window.","features":["12L capacity","2400W heating","Dual heating","LCD touchscreen","Viewing window"],"specifications":{"Capacity":"12L","Power":"2400W","Control":"LCD touchscreen"},"price":300000,"confidence":"High","imageSource":"Jumia Uganda Hoffmans Official Store","imageClean":False},
{"id":"hoffmans-hm718","slug":"hoffmans-hm718-14-in-1-pressure-cooker","brand":"Hoffmans","model":"HM-718","name":"Hoffmans 6L 14-in-1 Electric Pressure Cooker HM-718","category":"Pressure Cookers","description":"Hoffmans HM-718 6L multifunction electric pressure cooker with steamer and deep-fryer basket.","features":["14-in-1 functions","6L capacity","Pressure cooking","Steaming","Deep-fryer basket"],"specifications":{"Capacity":"6L","Functions":"14-in-1"},"price":300000,"confidence":"High","imageSource":"Jumia Uganda Hoffmans Official Store","imageClean":False},
{"id":"raf-3-5l-deep-fryer","slug":"raf-3-5l-electric-deep-fryer","brand":"RAF","model":"3.5L Electric Deep Fryer","name":"RAF 3.5L Electric Deep Fryer","category":"Quick Cooking","description":"RAF 3.5L electric deep fryer for controlled oil frying at home.","features":["3.5L capacity","Electric deep frying","Adjustable temperature","Frying basket"],"specifications":{"Capacity":"3.5L","Type":"Electric deep fryer"},"price":150000,"confidence":"High","imageSource":"Jumia Uganda RAF listing","imageClean":False},
{"id":"raf-12l-smart-air-fryer","slug":"raf-12l-smart-touch-air-fryer","brand":"RAF","model":"12L Smart Touch","name":"RAF 12L Smart Touch Oil-Free Digital Air Fryer","category":"Quick Cooking","description":"RAF 12L oil-free digital air fryer with smart touch controls.","features":["12L capacity","Digital touchscreen","Oil-free air frying","Adjustable temperature","Timer"],"specifications":{"Capacity":"12L","Control":"Smart touch"},"price":400000,"confidence":"High","imageSource":"Jumia Uganda RAF listing","imageClean":False},
{"id":"raf-8-in-1-2l-air-fryer","slug":"raf-8-in-1-2l-smart-air-fryer-oven","brand":"RAF","model":"8-in-1 2L Smart","name":"RAF 2L 8-in-1 Smart Digital Air Fryer Oven","category":"Quick Cooking","description":"RAF 2L multifunction digital air fryer oven with eight cooking functions.","features":["2L capacity","8-in-1 functions","Digital controls","Air frying","Oven cooking"],"specifications":{"Capacity":"2L","Functions":"8-in-1"},"price":400000,"confidence":"High","imageSource":"Jumia Uganda RAF listing","imageClean":False},
{"id":"raf-r5306-18l-electric-oven","slug":"raf-r5306-18l-electric-oven","brand":"RAF","model":"R-5306","name":"RAF 18L Electric Oven R-5306","category":"Quick Cooking","description":"RAF R-5306 countertop electric oven for baking and everyday quick cooking.","features":["18L capacity","Electric oven","Temperature control","Timer"],"specifications":{"Capacity":"18L","Type":"Countertop electric oven"},"price":300000,"confidence":"High","imageSource":"Jumia Uganda RAF listing","imageClean":False},
{"id":"pixel-6l-air-fryer","slug":"pixel-6l-digital-air-fryer","brand":"Pixel","model":"6L Digital Air Fryer","name":"Pixel 6L Digital Air Fryer","category":"Quick Cooking","description":"Pixel 6L digital air fryer for everyday low-oil cooking.","features":["6L capacity","Digital controls","Air frying","Adjustable temperature","Timer"],"specifications":{"Capacity":"6L","Control":"Digital"},"price":200000,"confidence":"Medium","imageSource":"Jumia Uganda Pixel Official Store listing","imageClean":False},
{"id":"raf-roti-maker-25cm","slug":"raf-25cm-1500w-roti-maker","brand":"RAF","model":"25cm 1500W Roti Maker","name":"RAF 25cm 1500W Roti Maker","category":"Quick Cooking","description":"RAF 25cm electric roti maker for quick flatbread preparation.","features":["25cm cooking plate","1500W heating","Electric operation","Non-stick cooking surface"],"specifications":{"Diameter":"25cm","Power":"1500W","Type":"Roti maker"},"price":220000,"confidence":"Medium","imageSource":"Jumia Uganda RAF listing","imageClean":False},
{"id":"raf-pizza-chapati-maker","slug":"raf-electric-pizza-chapati-maker","brand":"RAF","model":"Pizza/Chapati Maker","name":"RAF Electric Pizza & Chapati Maker","category":"Quick Cooking","description":"RAF electric countertop maker for pizza, chapati and flatbread preparation.","features":["Electric heating","Pizza preparation","Chapati preparation","Countertop design"],"specifications":{"Type":"Pizza and chapati maker"},"price":180000,"confidence":"Medium","imageSource":"Jumia Uganda RAF listing","imageClean":False},
{"id":"hisense-6l-air-fryer","slug":"hisense-6l-air-fryer","brand":"Hisense","model":"6L Air Fryer","name":"Hisense 6L Air Fryer","category":"Quick Cooking","description":"Hisense 6L air fryer for everyday low-oil frying and roasting.","features":["6L capacity","Air frying","Adjustable temperature","Timer"],"specifications":{"Capacity":"6L"},"price":300000,"confidence":"Medium","imageSource":"Jumia Uganda Hisense listing","imageClean":False},
{"id":"itel-iaf-001","slug":"itel-iaf-001-air-fryer","brand":"Itel","model":"IAF-001","name":"Itel IAF-001 Air Fryer","category":"Quick Cooking","description":"Itel IAF-001 compact air fryer for everyday cooking.","features":["Air frying","Adjustable temperature","Timer"],"specifications":{"Model":"IAF-001"},"price":200000,"confidence":"Medium","imageSource":"Jumia Uganda Itel listing","imageClean":False},
{"id":"global-star-7l-air-fryer","slug":"global-star-7l-digital-air-fryer","brand":"Global Star","model":"7L Multifunctional Digital Air Fryer","name":"Global Star 7L Multifunctional Digital Air Fryer","category":"Quick Cooking","description":"Global Star 7L digital air fryer with multifunction cooking controls.","features":["7L capacity","Digital controls","Multifunction cooking","Air frying"],"specifications":{"Capacity":"7L","Control":"Digital"},"price":237000,"confidence":"Medium","imageSource":"Jumia Uganda listing","imageClean":False},
{"id":"doraling-dr618","slug":"doraling-dr618-6l-air-fryer-oven","brand":"Doraling","model":"DR-618","name":"Doraling DR-618 6L Smart Touch Air Fryer Oven","category":"Quick Cooking","description":"Doraling DR-618 6L smart-touch countertop fryer and oven.","features":["6L capacity","Smart touch controls","Air frying","Oven cooking"],"specifications":{"Capacity":"6L","Control":"Smart touch"},"price":210000,"confidence":"Medium","imageSource":"Jumia Uganda listing","imageClean":False},
{"id":"silver-crest-6l-air-fryer","slug":"silver-crest-6l-air-fryer","brand":"Silver Crest","model":"6L Air Fryer","name":"Silver Crest 6L Air Fryer","category":"Quick Cooking","description":"Silver Crest 6L air fryer for everyday low-oil cooking.","features":["6L capacity","Air frying","Temperature control","Timer"],"specifications":{"Capacity":"6L"},"price":300000,"confidence":"Medium","imageSource":"Jumia Uganda listing","imageClean":False},
{"id":"tefal-ey801d27","slug":"tefal-ey801d27-6-5l-air-fryer-grill","brand":"Tefal","model":"EY801D27","name":"Tefal 6.5L Air Fryer & Grill EY801D27","category":"Quick Cooking","description":"Tefal EY801D27 6.5L air fryer and grill for versatile countertop cooking.","features":["6.5L capacity","Air frying","Grilling","Adjustable temperature","Timer"],"specifications":{"Capacity":"6.5L","Model":"EY801D27"},"price":815300,"confidence":"High","imageSource":"Tefal/Jumia Uganda exact-model listing","imageClean":False},
{"id":"tefal-ey501827","slug":"tefal-ey501827-4-2l-air-fryer-grill","brand":"Tefal","model":"EY501827","name":"Tefal 4.2L Air Fryer & Grill EY501827","category":"Quick Cooking","description":"Tefal EY501827 4.2L air fryer and grill for compact countertop cooking.","features":["4.2L capacity","Air frying","Grilling","Temperature control","Timer"],"specifications":{"Capacity":"4.2L","Model":"EY501827"},"price":548700,"confidence":"High","imageSource":"Tefal/Jumia Uganda exact-model listing","imageClean":False},
{"id":"raf-double-hot-plate","slug":"raf-stainless-steel-double-hot-plate","brand":"RAF","model":"Double Hot Plate","name":"RAF Stainless Steel Double Hot Plate","category":"Quick Cooking","description":"RAF stainless steel double electric hot plate for flexible countertop cooking.","features":["Two hot plates","Stainless steel body","Electric heating","Independent controls"],"specifications":{"Type":"Double hot plate"},"price":100000,"confidence":"High","imageSource":"Jumia Uganda RAF listing","imageClean":False},
{"id":"saachi-nl-1r-1172","slug":"saachi-nl-1r-1172-dry-iron","brand":"Saachi","model":"NL-1R-1172","name":"Saachi NL-1R-1172 Non-Stick Dry Iron","category":"Home Care","description":"Saachi NL-1R-1172 non-stick dry iron for everyday garment pressing.","features":["Non-stick soleplate","Dry ironing","Temperature control","Indicator light"],"specifications":{"Type":"Dry iron","Soleplate":"Non-stick"},"price":59981,"confidence":"High","imageSource":"Jumia Uganda Saachi listing","imageClean":False},
{"id":"saachi-nl-1r-158","slug":"saachi-nl-1r-158-heavy-weight-dry-iron","brand":"Saachi","model":"NL-1R-158","name":"Saachi NL-1R-158 Heavy-Weight Dry Iron","category":"Home Care","description":"Saachi NL-1R-158 heavy-weight dry iron for firm garment pressing.","features":["Heavy-weight design","Dry ironing","Temperature control","Indicator light"],"specifications":{"Type":"Dry iron","Model":"NL-1R-158"},"price":65000,"confidence":"High","imageSource":"Jumia Uganda Saachi listing","imageClean":False},
{"id":"pixel-1000w-dry-iron","slug":"pixel-1000w-dry-flat-iron","brand":"Pixel","model":"1000W Dry Flat Iron","name":"Pixel 1000W Dry Flat Iron","category":"Home Care","description":"Pixel 1000W dry flat iron for everyday garment pressing.","features":["1000W heating","Dry ironing","Temperature control","Indicator light"],"specifications":{"Power":"1000W","Type":"Dry iron"},"price":50000,"confidence":"High","imageSource":"Jumia Uganda Pixel Official Store listing","imageClean":False},
{"id":"spj-non-stick-dry-iron","slug":"spj-non-stick-dry-flat-iron","brand":"SPJ","model":"Non-Stick Dry Flat Iron","name":"SPJ Non-Stick Dry Flat Iron","category":"Home Care","description":"SPJ non-stick dry flat iron for everyday garment pressing.","features":["Non-stick soleplate","Dry ironing","Temperature control"],"specifications":{"Type":"Dry iron","Soleplate":"Non-stick"},"price":50000,"confidence":"Medium","imageSource":"Jumia Uganda SPJ listing","imageClean":False},
{"id":"hoffmans-hm9037","slug":"hoffmans-hm9037-heavy-dry-iron","brand":"Hoffmans","model":"HM-9037","name":"Hoffmans HM-9037 Heavy Dry Iron","category":"Home Care","description":"Hoffmans HM-9037 heavy dry iron for everyday garment pressing.","features":["Heavy dry iron","Temperature control","Indicator light","Ergonomic handle"],"specifications":{"Type":"Dry iron"},"price":69000,"confidence":"High","imageSource":"Jumia Uganda Hoffmans Official Store","imageClean":False},
{"id":"hoffmans-hm9029","slug":"hoffmans-hm9029-steam-dry-iron","brand":"Hoffmans","model":"HM-9029","name":"Hoffmans HM-9029 Steam & Dry Flat Iron","category":"Home Care","description":"Hoffmans HM-9029 flat iron supporting both steam and dry ironing.","features":["Steam ironing","Dry ironing","Temperature control","Water tank"],"specifications":{"Type":"Steam and dry iron"},"price":65000,"confidence":"High","imageSource":"Jumia Uganda Hoffmans Official Store","imageClean":False},
{"id":"hoffmans-hm9053","slug":"hoffmans-hm9053-3000w-steam-iron","brand":"Hoffmans","model":"HM-9053","name":"Hoffmans HM-9053 3000W Steam Iron","category":"Home Care","description":"Hoffmans HM-9053 high-power steam iron for garment care.","features":["3000W heating","Steam ironing","Temperature control","Water tank"],"specifications":{"Power":"3000W","Type":"Steam iron"},"price":100000,"confidence":"High","imageSource":"Jumia Uganda Hoffmans Official Store","imageClean":False},
{"id":"hoffmans-hm9062","slug":"hoffmans-hm9062-high-power-steam-iron","brand":"Hoffmans","model":"HM-9062","name":"Hoffmans HM-9062 High-Power Steam Iron","category":"Home Care","description":"Hoffmans HM-9062 steam iron with high-power heating for everyday pressing.","features":["Steam ironing","High-power heating","Temperature control","Water tank"],"specifications":{"Type":"Steam iron"},"price":100000,"confidence":"High","imageSource":"Jumia Uganda Hoffmans Official Store","imageClean":False},
{"id":"hoffmans-cordless-steam-iron","slug":"hoffmans-cordless-2200-2400w-steam-iron","brand":"Hoffmans","model":"Cordless 2200–2400W","name":"Hoffmans Cordless 2200–2400W Steam Iron","category":"Home Care","description":"Hoffmans cordless steam iron with ceramic soleplate and large water tank.","features":["Cordless operation","Steam ironing","Ceramic soleplate","Anti-calc","Large water tank"],"specifications":{"Power":"2200–2400W","Type":"Cordless steam iron","Tank":"450ml"},"price":150000,"confidence":"Medium","imageSource":"Jumia Uganda Hoffmans listing","imageClean":False},
{"id":"hisense-h18sigrs1","slug":"hisense-h18sigrs1-1800w-steam-iron","brand":"Hisense","model":"H18SIGRS1","name":"Hisense H18SIGRS1 1800W Steam Iron","category":"Home Care","description":"Hisense H18SIGRS1 1800W steam iron with a 250ml water tank.","features":["1800W heating","Steam ironing","250ml tank","Temperature control"],"specifications":{"Power":"1800W","Tank":"250ml","Type":"Steam iron"},"price":150000,"confidence":"High","imageSource":"Jumia Uganda Hisense Official Store","imageClean":False},
{"id":"sonifer-steam-iron-ceramic","slug":"sonifer-ceramic-sole-steam-iron","brand":"Sonifer","model":"Ceramic Sole Steam Iron","name":"Sonifer Ceramic-Sole Steam Iron","category":"Home Care","description":"Sonifer steam iron with ceramic soleplate for everyday garment care.","features":["Ceramic soleplate","Steam ironing","Temperature control","Water tank"],"specifications":{"Type":"Steam iron","Soleplate":"Ceramic"},"price":98000,"confidence":"Medium","imageSource":"Jumia Uganda Sonifer listing","imageClean":False},
{"id":"winningstar-steam-iron-ceramic","slug":"winningstar-ceramic-sole-steam-iron","brand":"Winningstar","model":"Ceramic Sole Steam Iron","name":"Winningstar Ceramic-Sole Steam Iron","category":"Home Care","description":"Winningstar steam iron with ceramic soleplate for everyday pressing.","features":["Ceramic soleplate","Steam ironing","Temperature control","Water tank"],"specifications":{"Type":"Steam iron","Soleplate":"Ceramic"},"price":120000,"confidence":"Medium","imageSource":"Jumia Uganda Winningstar listing","imageClean":False},
{"id":"sokany-yg888","slug":"sokany-yg-888-garment-steamer","brand":"Sokany","model":"YG-888","name":"Sokany YG-888 Garment Steamer","category":"Home Care","description":"Sokany YG-888 handheld garment steamer for quick wrinkle removal.","features":["Handheld design","Continuous steaming","Compact form","Fast heating"],"specifications":{"Model":"YG-888","Type":"Handheld garment steamer"},"price":156000,"confidence":"High","imageSource":"Jumia Uganda Sokany listing","imageClean":False},
{"id":"panasonic-nighd015","slug":"panasonic-nighd015-steam-iron","brand":"Panasonic","model":"NIGHD015","name":"Panasonic NIGHD015 Steam Iron","category":"Home Care","description":"Panasonic NIGHD015 steam iron for everyday garment pressing.","features":["Steam ironing","Temperature control","Water tank","Non-stick soleplate"],"specifications":{"Model":"NIGHD015","Type":"Steam iron"},"price":250000,"confidence":"Medium","imageSource":"Jumia Uganda Panasonic listing","imageClean":False},
{"id":"geepas-ggs25022","slug":"geepas-ggs25022-2000w-garment-steamer","brand":"Geepas","model":"GGS25022","name":"Geepas GGS25022 2000W Garment Steamer","category":"Home Care","description":"Geepas GGS25022 2000W garment and fabric steamer with a 1.8L water tank.","features":["2000W heating","1.8L tank","Garment steaming","Fabric steaming"],"specifications":{"Power":"2000W","Tank":"1.8L","Type":"Garment/fabric steamer"},"price":200000,"confidence":"High","imageSource":"Jumia Uganda Geepas listing","imageClean":False},
{"id":"hoffmans-hm9080","slug":"hoffmans-hm9080-upright-garment-steamer","brand":"Hoffmans","model":"HM-9080","name":"Hoffmans HM-9080 2-in-1 Upright Garment Steamer","category":"Home Care","description":"Hoffmans HM-9080 upright garment steamer with 2L tank and integrated ironing board.","features":["2000W heating","2L tank","Upright steaming","Integrated ironing board","2-in-1 design"],"specifications":{"Power":"2000W","Tank":"2L","Type":"Upright garment steamer"},"price":200000,"confidence":"High","imageSource":"Jumia Uganda Hoffmans Official Store","imageClean":False},
{"id":"hoffmans-hm9038","slug":"hoffmans-hm9038-1500w-handheld-steamer","brand":"Hoffmans","model":"HM-9038","name":"Hoffmans HM-9038 1500W Handheld Garment Steamer","category":"Home Care","description":"Hoffmans HM-9038 1500W handheld garment steamer for quick wrinkle removal.","features":["1500W heating","Handheld design","Fast heating","Garment steaming"],"specifications":{"Power":"1500W","Type":"Handheld garment steamer"},"price":95000,"confidence":"High","imageSource":"Jumia Uganda Hoffmans Official Store","imageClean":False},
{"id":"raf-r1313","slug":"raf-r1313-handheld-garment-steamer","brand":"RAF","model":"R1313","name":"RAF R1313 Handheld Garment Steamer","category":"Home Care","description":"RAF R1313 handheld garment steamer with a 120ml water tank for quick fabric steaming.","features":["120ml tank","30-second reheating","Handheld design","Continuous steaming"],"specifications":{"Model":"R1313","Tank":"120ml","Type":"Handheld garment steamer"},"price":75000,"confidence":"High","imageSource":"Jumia Uganda RAF Official Store","imageClean":False},
{"id":"raf-1700ml-vertical-steamer","slug":"raf-1700ml-vertical-garment-steamer","brand":"RAF","model":"1700ml Vertical","name":"RAF 1700ml Vertical Garment Steamer","category":"Home Care","description":"RAF vertical garment steamer with a 1700ml water tank for upright fabric care.","features":["1700ml tank","Vertical steaming","Adjustable steaming","Garment care"],"specifications":{"Tank":"1700ml","Type":"Vertical garment steamer"},"price":200000,"confidence":"High","imageSource":"Jumia Uganda RAF listing","imageClean":False},
{"id":"raf-1700w-garment-steamer","slug":"raf-1700w-garment-steamer","brand":"RAF","model":"1700W Garment Steamer","name":"RAF 1700W Garment Steamer","category":"Home Care","description":"RAF 1700W garment steamer for hanging clothes and everyday wrinkle removal.","features":["1700W heating","Garment steaming","Hanging steaming","Fast heating"],"specifications":{"Power":"1700W","Type":"Garment steamer"},"price":200000,"confidence":"Medium","imageSource":"Jumia Uganda RAF listing","imageClean":False},
{"id":"raf-mw3018","slug":"raf-mw-3018-1500w-garment-steamer","brand":"RAF","model":"MW-3018","name":"RAF MW-3018 1500W Garment Steamer","category":"Home Care","description":"RAF MW-3018 1500W garment steamer for everyday fabric care.","features":["1500W heating","Garment steaming","Fast heating","Wrinkle removal"],"specifications":{"Power":"1500W","Model":"MW-3018"},"price":500000,"confidence":"Medium","imageSource":"Jumia Uganda RAF listing","imageClean":False},
{"id":"sonifer-garment-steamer","slug":"sonifer-garment-steamer","brand":"Sonifer","model":"Garment Steamer","name":"Sonifer Garment Steamer","category":"Home Care","description":"Sonifer garment steamer for upright and everyday wrinkle removal.","features":["Garment steaming","Continuous steam","Fabric care"],"specifications":{"Type":"Garment steamer"},"price":400100,"confidence":"Medium","imageSource":"Jumia Uganda Sonifer listing","imageClean":False},
]
# Prevent duplicates against existing normalized models/ids/slugs and within candidates.
def norm(x):
 import re
 return re.sub(r'[^a-z0-9]','',x or '').lower()
existing_ids=set(re.findall(r"id:'([^']+)'",s))
existing_slugs=set(re.findall(r"slug:'([^']+)'",s))
existing_models={norm(x) for x in re.findall(r"model:'([^']+)'",s)}
added=[]
for it in items:
 if it['id'] in existing_ids or it['slug'] in existing_slugs or norm(it['model']) in existing_models:
  continue
 # TS literal
 def q(v): return "'"+str(v).replace("'","\\'")+"'"
 fields=[f"id:{q(it['id'])}",f"slug:{q(it['slug'])}",f"brand:{q(it['brand'])}",f"model:{q(it['model'])}",f"name:{q(it['name'])}",f"category:{q(it['category'])}",f"description:{q(it['description'])}","features:["+','.join(q(x) for x in it['features'])+"]","specifications:{"+','.join(q(k)+':'+q(v) for k,v in it['specifications'].items())+"}",f"price:{it['price']}","currency:'UGX'",f"availability:'in-stock'",f"confidence:{q(it['confidence'])}",f"imageSource:{q(it['imageSource'])}",f"imageClean:{str(it['imageClean']).lower()}"]
 added.append('{'+','.join(fields)+'},')
 existing_ids.add(it['id']); existing_slugs.add(it['slug']); existing_models.add(norm(it['model']))
new_s=s.replace(marker,'\n'+ '\n'.join(added) + marker)
p.write_text(new_s)
print('added',len(added))
print('\n'.join(x.split(',',1)[0] for x in added))
