import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  images: {
    // Remote catalogue images are rendered directly in the browser. This avoids the Next.js 50-pattern ceiling while preserving all researched image URLs.
    unoptimized: true,
    remotePatterns: [
      { protocol: 'https', hostname: 'aksesore.al' },
      { protocol: 'https', hostname: 'ambulantenligne.com' },
      { protocol: 'https', hostname: 'cafershopp.com' },
      { protocol: 'https', hostname: 'capital.munoclub.com' },
      { protocol: 'https', hostname: 'cdn-img.oraimo.com' },
      { protocol: 'https', hostname: 'cdn.asaxiy.uz' },
      { protocol: 'https', hostname: 'cdn.bdstall.com' },
      { protocol: 'https', hostname: 'cdn.bestsuppliers.com' },
      { protocol: 'https', hostname: 'cdn.ourshopee.com' },
      { protocol: 'https', hostname: 'content1.rozetka.com.ua' },
      { protocol: 'https', hostname: 'dearhome.me' },
      { protocol: 'https', hostname: 'f.fcdn.app' },
      { protocol: 'https', hostname: 'goodprice.ug' },
      { protocol: 'https', hostname: 'hisense.co.za' },
      { protocol: 'https', hostname: 'i0.wp.com' },
      { protocol: 'https', hostname: 'i5.walmartimages.cl' },
      { protocol: 'https', hostname: 'images.philips.com' },
      { protocol: 'https', hostname: 'images.prom.ua' },
      { protocol: 'https', hostname: 'images.samsung.com' },
      { protocol: 'https', hostname: 'kibuga-assets.fra1.cdn.digitaloceanspaces.com' },
      { protocol: 'https', hostname: 'lifestoresuganda.com' },
      { protocol: 'https', hostname: 'm2.dantty.com' },
      { protocol: 'https', hostname: 'media.abanista.com' },
      { protocol: 'https', hostname: 'media3.bsh-group.com' },
      { protocol: 'https', hostname: 'midea.com' },
      { protocol: 'https', hostname: 'nelooq.com' },
      { protocol: 'https', hostname: 'newmatic.com' },
      { protocol: 'https', hostname: 'newmaticug.com' },
      { protocol: 'https', hostname: 'paylessphotolb.com' },
      { protocol: 'https', hostname: 'planetgate.net' },
      { protocol: 'https', hostname: 'primeelectronicsug.com' },
      { protocol: 'https', hostname: 'qsales.qa' },
      { protocol: 'https', hostname: 's.alicdn.com' },
      { protocol: 'https', hostname: 'spacenet.tn' },
      { protocol: 'https', hostname: 'static-data2.manualslib.com' },
      { protocol: 'https', hostname: 'uae.geepas.com' },
      { protocol: 'https', hostname: 'ug.jumia.is' },
      { protocol: 'https', hostname: 'web-res.midea.com' },
      { protocol: 'https', hostname: 'www.beko.com' },
      { protocol: 'https', hostname: 'www.blackanddecker.ae' },
      { protocol: 'https', hostname: 'www.dombelo.com' },
      { protocol: 'https', hostname: 'www.domesticappliances.philips.co.in' },
      { protocol: 'https', hostname: 'www.dubaizones.com' },
      { protocol: 'https', hostname: 'www.instok.co.ke' },
      { protocol: 'https', hostname: 'www.kenyatronics.com' },
      { protocol: 'https', hostname: 'www.lg.com' },
      { protocol: 'https', hostname: 'www.midea.com' },
      { protocol: 'https', hostname: 'www.raf-china.com' },
      { protocol: 'https', hostname: 'www.tilyexpress.ug' },
      { protocol: 'https', hostname: 'z.nooncdn.com' },
      { protocol: 'https', hostname: 'americanas.vtexassets.com' },
      { protocol: 'https', hostname: 'down-my.img.susercontent.com' },
      { protocol: 'https', hostname: 'geepas.co.uk' },
      { protocol: 'https', hostname: 'i5.walmartimages.com' },
      { protocol: 'https', hostname: 'image.made-in-china.com' },
      { protocol: 'https', hostname: 'jomla-erp.b-cdn.net' },
      { protocol: 'https', hostname: 'med.greatecno.com' },
      { protocol: 'https', hostname: 'media.diy.com' },
      { protocol: 'https', hostname: 'www.panasonic.com' },
    ],
  },
};

export default nextConfig;
