import type { NextConfig } from 'next';
const nextConfig: NextConfig = { images: { remotePatterns: [
  { protocol:'https', hostname:'upload.wikimedia.org' },
  { protocol:'https', hostname:'www.lg.com' },
  { protocol:'https', hostname:'cdn.simpleicons.org' },
  { protocol:'https', hostname:'images.samsung.com' },
  { protocol:'https', hostname:'images.philips.com' },
  { protocol:'https', hostname:'www.tilyexpress.ug' },
  { protocol:'https', hostname:'i0.wp.com' },
  { protocol:'https', hostname:'cdn.bdstall.com' },
  { protocol:'https', hostname:'planetgate.net' },
  { protocol:'https', hostname:'www.raflebanon.com' },
  { protocol:'https', hostname:'strausaustria.hu' },
  { protocol:'https', hostname:'qsales.qa' },
  { protocol:'https', hostname:'web-res.midea.com' },
  { protocol:'https', hostname:'www.domesticappliances.philips.co.in' },
  { protocol:'https', hostname:'images.prom.ua' },
  { protocol:'https', hostname:'kibuga-assets.fra1.cdn.digitaloceanspaces.com' },
  { protocol:'https', hostname:'m2.dantty.com' },
  { protocol:'https', hostname:'s.alicdn.com' },
  { protocol:'https', hostname:'ug.jumia.is' },
  { protocol:'https', hostname:'i5.walmartimages.cl' },
  { protocol:'https', hostname:'nelooq.com' },
  { protocol:'https', hostname:'content1.rozetka.com.ua' },
  { protocol:'https', hostname:'cdn-img.oraimo.com' },
  { protocol:'https', hostname:'www.arizon.az' },
  { protocol:'https', hostname:'cdn.bestsuppliers.com' },
  { protocol:'https', hostname:'spacenet.tn' },
  { protocol:'https', hostname:'paylessphotolb.com' },
  { protocol:'https', hostname:'static.kupindoslike.com' },
  { protocol:'https', hostname:'www.raf-china.com' },
  { protocol:'https', hostname:'lifestoresuganda.com' },
  { protocol:'https', hostname:'aksesore.al' },
  { protocol:'https', hostname:'cafershopp.com' },
] } };
export default nextConfig;
