import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'www.beko.com' },
      { protocol: 'https', hostname: 'www.lg.com' },
      { protocol: 'https', hostname: 'images.samsung.com' },
      { protocol: 'https', hostname: 'ug.jumia.is' },
      { protocol: 'https', hostname: 'www.tilyexpress.ug' },
      { protocol: 'https', hostname: 'i0.wp.com' },
      { protocol: 'https', hostname: 'cdn.bdstall.com' },
      { protocol: 'https', hostname: 'planetgate.net' },
      { protocol: 'https', hostname: 'cafershopp.com' },
      { protocol: 'https', hostname: 'aksesore.al' },
      { protocol: 'https', hostname: 'qsales.qa' },
      { protocol: 'https', hostname: 'web-res.midea.com' },
      { protocol: 'https', hostname: 'www.domesticappliances.philips.co.in' },
      { protocol: 'https', hostname: 'nelooq.com' },
      { protocol: 'https', hostname: 'content1.rozetka.com.ua' },
      { protocol: 'https', hostname: 'cdn-img.oraimo.com' },
      { protocol: 'https', hostname: 'm2.dantty.com' },
      { protocol: 'https', hostname: 'kibuga-assets.fra1.cdn.digitaloceanspaces.com' },
      { protocol: 'https', hostname: 's.alicdn.com' },
      { protocol: 'https', hostname: 'www.raf-china.com' },
      { protocol: 'https', hostname: 'paylessphotolb.com' },
      { protocol: 'https', hostname: 'spacenet.tn' },
      { protocol: 'https', hostname: 'cdn.bestsuppliers.com' },
      { protocol: 'https', hostname: 'i5.walmartimages.cl' },
      { protocol: 'https', hostname: 'lifestoresuganda.com' },
      { protocol: 'https', hostname: 'images.prom.ua' },
      { protocol: 'https', hostname: 'f.fcdn.app' },
      { protocol: 'https', hostname: 'goodprice.ug' },
      { protocol: 'https', hostname: 'www.midea.com' },
      { protocol: 'https', hostname: 'www.instok.co.ke' },
      { protocol: 'https', hostname: 'www.dombelo.com' },
      { protocol: 'https', hostname: 'media.abanista.com' },
      { protocol: 'https', hostname: 'cdn.asaxiy.uz' },
      { protocol: 'https', hostname: 'newmatic.com' },
      { protocol: 'https', hostname: 'static-data2.manualslib.com' },
      { protocol: 'https', hostname: 'ambulantenligne.com' },
      { protocol: 'https', hostname: 'capital.munoclub.com' },
      { protocol: 'https', hostname: 'www.kenyatronics.com' },
      { protocol: 'https', hostname: 'z.nooncdn.com' },
    ],
  },
};

export default nextConfig;
