'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { useCartStore } from '@/lib/cart-store';
import { formatUGX } from '@/lib/catalogue';
import { ArrowLeft, ArrowRight, ShieldCheck } from 'lucide-react';

const schema=z.object({name:z.string().min(2,'Enter your full name.'),phone:z.string().min(9,'Enter a valid phone number.'),email:z.string().email('Enter a valid email.').optional().or(z.literal('')),location:z.string().min(2,'Enter your delivery location.'),payment:z.enum(['cash-on-delivery','mobile-money','bank-transfer'])});
type FormData=z.infer<typeof schema>;
export default function Checkout(){
 const router=useRouter(); const items=useCartStore((s)=>s.items); const clear=useCartStore((s)=>s.clear); const subtotal=items.reduce((sum,i)=>sum+i.price*i.quantity,0);
 const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<FormData>({resolver:zodResolver(schema),defaultValues:{payment:'mobile-money'}});
 const onSubmit=(data:FormData)=>{ if(!items.length)return; const order=`AMA-${Date.now().toString().slice(-8)}`; sessionStorage.setItem('amaal-last-order',JSON.stringify({order,data,items,total:subtotal})); clear(); router.push(`/order-confirmation?order=${order}`); };
 if(!items.length) return <main className="section"><div className="container empty-state"><div className="eyebrow">Checkout</div><h1>No items to checkout.</h1><p className="muted">Your bag is empty.</p><Link className="btn" href="/shop">Shop products</Link></div></main>;
 return <main className="section checkout-page"><div className="container"><Link className="back-link" href="/cart"><ArrowLeft size={15}/> Back to bag</Link><div className="checkout-heading"><div><div className="eyebrow">Checkout</div><h1>Complete your order</h1><p className="muted">A few details and your preferred payment method.</p></div><div className="checkout-trust"><ShieldCheck size={18}/><span>Ready to place your order</span></div></div><div className="checkout-layout"><form className="checkout-form" onSubmit={handleSubmit(onSubmit)}><div className="form-section"><h2>Delivery details</h2><label>Full name<input {...register('name')} placeholder="Your full name" autoComplete="name"/>{errors.name&&<small>{errors.name.message}</small>}</label><label>Phone number<input {...register('phone')} placeholder="07xx xxx xxx" autoComplete="tel"/>{errors.phone&&<small>{errors.phone.message}</small>}</label><label>Email <span>(optional)</span><input {...register('email')} placeholder="you@example.com" autoComplete="email"/>{errors.email&&<small>{errors.email.message}</small>}</label><label>Delivery location<input {...register('location')} placeholder="Area, town/city" autoComplete="street-address"/>{errors.location&&<small>{errors.location.message}</small>}</label></div><div className="form-section"><h2>Payment preference</h2><label className="radio-card"><input type="radio" value="mobile-money" {...register('payment')}/><span><strong>Mobile money</strong><small>Preferred local payment option</small></span></label><label className="radio-card"><input type="radio" value="cash-on-delivery" {...register('payment')}/><span><strong>Cash on delivery</strong><small>Pay when the order is delivered</small></span></label><label className="radio-card"><input type="radio" value="bank-transfer" {...register('payment')}/><span><strong>Bank transfer</strong><small>Arrange transfer with Amaal</small></span></label></div><button className="btn full checkout-submit" disabled={isSubmitting}>Place order <ArrowRight size={17}/></button><p className="muted small">Your order will be confirmed with you before delivery. Payment and delivery details are arranged with Amaal.</p></form><aside className="checkout-summary"><div className="eyebrow">Your order</div>{items.map(i=><div className="summary-item" key={i.id}><span>{i.name} × {i.quantity}</span><strong>{formatUGX(i.price*i.quantity)}</strong></div>)}<div className="summary-row total"><span>Total</span><strong>{formatUGX(subtotal)}</strong></div><div className="checkout-note">✓ Your selected products<br/>✓ Clear UGX pricing<br/>✓ Delivery details confirmed with you</div></aside></div></div></main>;
}
